# Database Connection properties
jdbc.driverClassName=org.postgresql.Driver
jdbc.url=jdbc:postgresql://ep-falling-union-andn2ie9.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
jdbc.user=neondb_owner
jdbc.pass=npg_8tFvyEPX5dsf

# Server Settings
server.port=8082
